ruleArchive: latest
policies:
    - WCAG_2_1
# failLevels:
#     - violation
#     - potentialviolation
reportLevels:
    - violation
    - potentialviolation
    - recommendation
    - potentialrecommendation
    - manual
outputFormat:
    - json